// Code generated by Kitex v0.12.1. DO NOT EDIT.

package openccservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	opencc_service "openccapi/rpc/opencc/kitex_gen/demo/opencc_service"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Convert(ctx context.Context, Req *opencc_service.ConvertRequest, callOptions ...callopt.Option) (r *opencc_service.ConvertResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kOpenCCServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOpenCCServiceClient struct {
	*kClient
}

func (p *kOpenCCServiceClient) Convert(ctx context.Context, Req *opencc_service.ConvertRequest, callOptions ...callopt.Option) (r *opencc_service.ConvertResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Convert(ctx, Req)
}
