// Code generated by Kitex v0.12.1. DO NOT EDIT.

package openccservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	opencc_service "openccapi/rpc/opencc/kitex_gen/demo/opencc_service"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Convert": kitex.NewMethodInfo(
		convertHandler,
		newConvertArgs,
		newConvertResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	openCCServiceServiceInfo                = NewServiceInfo()
	openCCServiceServiceInfoForClient       = NewServiceInfoForClient()
	openCCServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return openCCServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return openCCServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return openCCServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OpenCCService"
	handlerType := (*opencc_service.OpenCCService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "opencc_service",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.1",
		Extra:           extra,
	}
	return svcInfo
}

func convertHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(opencc_service.ConvertRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(opencc_service.OpenCCService).Convert(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ConvertArgs:
		success, err := handler.(opencc_service.OpenCCService).Convert(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ConvertResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newConvertArgs() interface{} {
	return &ConvertArgs{}
}

func newConvertResult() interface{} {
	return &ConvertResult{}
}

type ConvertArgs struct {
	Req *opencc_service.ConvertRequest
}

func (p *ConvertArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(opencc_service.ConvertRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ConvertArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ConvertArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ConvertArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConvertArgs) Unmarshal(in []byte) error {
	msg := new(opencc_service.ConvertRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConvertArgs_Req_DEFAULT *opencc_service.ConvertRequest

func (p *ConvertArgs) GetReq() *opencc_service.ConvertRequest {
	if !p.IsSetReq() {
		return ConvertArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConvertArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConvertArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConvertResult struct {
	Success *opencc_service.ConvertResponse
}

var ConvertResult_Success_DEFAULT *opencc_service.ConvertResponse

func (p *ConvertResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(opencc_service.ConvertResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ConvertResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ConvertResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ConvertResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConvertResult) Unmarshal(in []byte) error {
	msg := new(opencc_service.ConvertResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConvertResult) GetSuccess() *opencc_service.ConvertResponse {
	if !p.IsSetSuccess() {
		return ConvertResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConvertResult) SetSuccess(x interface{}) {
	p.Success = x.(*opencc_service.ConvertResponse)
}

func (p *ConvertResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConvertResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Convert(ctx context.Context, Req *opencc_service.ConvertRequest) (r *opencc_service.ConvertResponse, err error) {
	var _args ConvertArgs
	_args.Req = Req
	var _result ConvertResult
	if err = p.c.Call(ctx, "Convert", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
