// Code generated by Kitex v0.12.1. DO NOT EDIT.
package openccservice

import (
	server "github.com/cloudwego/kitex/server"
	opencc_service "openccapi/rpc/opencc/kitex_gen/demo/opencc_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler opencc_service.OpenCCService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler opencc_service.OpenCCService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
